using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Utm_market.Core.Entities;
using Utm_market.Core.Filters;

namespace Utm_market.Core.Repositories;

/// <summary>
/// Defines the contract for the Sale aggregate root repository, abstracting persistence details.
/// Designed for Native AOT compatibility and optimized for data streaming.
/// </summary>
public interface ISaleRepository
{
    /// <summary>
    /// Retrieves all sales asynchronously as a data stream.
    /// This allows processing sales one by one without loading the entire collection into memory,
    /// ideal for large datasets and console environments in .NET 10.
    /// </summary>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>An IAsyncEnumerable of Sale objects.</returns>
    IAsyncEnumerable<Sale> GetAllAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Retrieves a sale by its unique identifier asynchronously.
    /// </summary>
    /// <param name="saleId">The unique identifier of the sale.</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>A task representing the asynchronous operation. The result is the found sale or null if it does not exist.</returns>
    Task<Sale?> GetByIdAsync(int saleId, CancellationToken cancellationToken = default);

    /// <summary>
    /// Searches for sales that match the criteria specified in the filter.
    /// </summary>
    /// <param name="filter">SaleFilter object with search criteria.</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>An IAsyncEnumerable of Sale objects that match the filter.</returns>
    IAsyncEnumerable<Sale> FindAsync(SaleFilter filter, CancellationToken cancellationToken = default);

    /// <summary>
    /// Adds a new sale to the system asynchronously.
    /// </summary>
    /// <param name="sale">The Sale object to add.</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>A task representing the asynchronous operation. The result is the added sale, including any ID generated by persistence.</returns>
    Task<Sale> AddAsync(Sale sale, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates an existing sale in the system asynchronously.
    /// </summary>
    /// <param name="sale">The Sale object with updated data.</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>A task representing the asynchronous operation. The result is a boolean indicating if the update was successful.</returns>
    Task<bool> UpdateAsync(Sale sale, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates the status of a specific sale atomically.
    /// </summary>
    /// <param name="saleId">The unique identifier of the sale to update.</param>
    /// <param name="newStatus">The new status of the sale.</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>A task representing the asynchronous operation. The result is a boolean indicating if the update was successful.</returns>
    Task<bool> UpdateStatusAsync(int saleId, SaleStatus newStatus, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a sale by its unique identifier asynchronously.
    /// </summary>
    /// <param name="saleId">The unique identifier of the sale to delete.</param>
    /// <param name="cancellationToken">Token to cancel the asynchronous operation.</param>
    /// <returns>A task representing the asynchronous operation. The result is a boolean indicating if the deletion was successful.</returns>
    Task<bool> DeleteAsync(int saleId, CancellationToken cancellationToken = default);
}
